const KRANK_LEHREN = {
  /* Ära 7.5 (Lehr-Audit #14): "um über 30 Prozent" -> "um über 30 Prozentpunkte" (Liu et al. 2023). */
  kontextrot: "Kontextrot ist real — aber es ist ein Zustand der laufenden Sitzung bzw. Anfrage (überfüllter, zerfaserter Kontext), keine Krankheit der Modellgewichte: Der Chroma-Report 2025 testete 18 Modelle (u.a. GPT-4.1, Claude 4, Gemini 2.5, Qwen3) und fand, dass die Leistung mit wachsender Eingabelänge ungleichmäßig sinkt — selbst bei simplen Aufgaben, und Ablenker-Texte verschärfen den Abfall (Chroma-Report 2025). Schon Liu et al. 2023 zeigten: Steht die relevante Info in der Mitte eines langen Kontexts, fällt die Trefferquote um über 30 Prozentpunkte ('Lost in the Middle'). Heilung heißt deshalb: die Sitzung bzw. den Kontext bereinigen — Kompaktierung (wie /compact in Claude Code), eine frische Sitzung mit sauberem Kontext und Retrieval statt Vollstopfen, nur die wirklich relevanten Auszüge laden. Ein Memory-Baustein kann dabei helfen, ist aber keine Heilgarantie.",
  /* Ära 7.5 (Lehr-Audit #8): SimpleQA (closed book, reines Erinnern) und Vectara HHEM
     (Abweichung von einem MITGELIEFERTEN Dokument) messen Verschiedenes – die beiden
     Prozentzahlen standen vorher unkommentiert nebeneinander und legten eine Ableitung nahe,
     die es nicht gibt. */
  halluzinose: "Modelle halluzinieren, weil Training und Benchmarks mutiges Raten belohnen und ein ehrliches 'Ich weiß es nicht' bestrafen (OpenAI-Paper 'Why Language Models Hallucinate', 2025) — und weil ohne Grounding schlicht die Quellen fehlen: Wo Wissen veraltet ist oder nie da war, rät das Modell. Wie schlimm es ohne Quellen wird, zeigt die eigene Model Card von gpt-oss-120b: 78 Prozent Fehlerquote auf SimpleQA (OpenAI Model Card 2025) — dieser Test misst reines Erinnern, ohne jedes mitgelieferte Dokument. Etwas ganz anderes misst das Vectara-Leaderboard (HHEM): Dort bekommt das Modell einen Text und es wird geprüft, ob die Zusammenfassung von diesem Text abweicht; gute Modelle bleiben da unter 2 Prozent. Die beiden Zahlen sind NICHT verrechenbar — es sind zwei verschiedene Messungen, und aus 78 gegen 2 folgt nicht, dass RAG die Halluzinationen auf ein Vierzigstel drückt. Beide zeigen aber dasselbe Prinzip: Mit Quelle im Kontext rät ein Modell deutlich weniger. Echte Heilmittel: eine Faktenkur — RAG-Quellen aktualisieren und Antworten an Quellen binden (Grounding) —, Abstention-Training (Enthaltung belohnen statt bestrafen), Faktentuning per DPO und niedrigere Temperatur mit Zitierpflicht. Schlaf heilt Halluzinose nicht.",
  uebertrainiert: "Wer zu hart oder zu schnell feintuned, löst katastrophales Vergessen aus: Das Modell überschreibt sein Vorwissen mit den neuen Daten (dokumentiert u.a. in EMNLP-Findings 2024). Der Schaden entsteht durch das Training und steckt danach in den Gewichten selbst — Ausruhen lässt ihn nicht verschwinden, nur ein Rollback zum früheren Checkpoint stellt den alten Stand wieder her. Deshalb sind Checkpoints plus Rollback DIE Standardpraxis jedes ernsthaften Trainingslaufs — beim OPT-175B-Training wurde bei Loss-Sprüngen dutzendfach zum früheren Checkpoint zurückgerollt und die Lernrate gesenkt (OPT-Logbuch, Meta 2022). Vorbeugend helfen Early Stopping, 10 bis 30 Prozent Originaldaten als Replay beimischen (Continual-Learning-Forschung) — und erst in Ruhe evaluieren, bevor weitertrainiert wird.",
  schleifenfieber: "Gierige Dekodierung (immer nur das wahrscheinlichste Wort) treibt Modelle in endlose Wiederholungsschleifen — nachgewiesen von Holtzman et al. 2019, deren Nucleus Sampling (Top-p) zum Standard-Gegenmittel wurde. Die Qwen3 Model Card warnt wörtlich vor Greedy Decoding und empfiehlt Temperatur 0,6, Top-p 0,95 und eine Presence Penalty bis 1,5 gegen Endlos-Wiederholungen (Qwen3 Model Card 2025). Und Vorsicht beim Futter: Unkritisches rekursives Training auf den eigenen synthetischen Ausgaben kann Modelle kollabieren lassen — die seltenen Randfälle verschwinden zuerst (Shumailov et al., Nature 2024). Das ist ein reales Risiko, kein Naturgesetz — frische menschliche Daten halten die Vielfalt am Leben."
};
const WISSEN_KRANK = [
  /* Ära 7.5 (Lehr-Audit #14): Prozentpunkte statt Prozent. */
  {kat:"betrieb", t:"Kontextrot ist messbar", txt:"Der Chroma-Report 2025 vermaß 18 Modelle: Mehr Kontext macht Antworten nicht besser, sondern ab einem Punkt schlechter — im LongMemEval-Test schlug ein fokussierter Auszug von rund 300 Tokens den vollen 113.000-Token-Kontext deutlich (Chroma-Report 2025). Und Infos in der Kontextmitte gehen am ehesten verloren, über 30 Prozentpunkte Einbruch bei der Trefferquote (Liu et al. 2023, 'Lost in the Middle'). Das Rot sitzt in der Sitzung, nicht in den Gewichten — Profis helfen sich mit Kompaktierung, frischen Sitzungen und Retrieval statt Vollstopfen; ein Memory-Baustein allein garantiert keine Heilung."},
  /* Ära 7.5 (Lehr-Audit #8): SimpleQA und Vectara HHEM ausdrücklich als zwei Messungen getrennt. */
  {kat:"sicherheit", t:"Warum Modelle halluzinieren", txt:"OpenAI erklärt es 2025 selbst: Benchmarks belohnen mutiges Raten und bestrafen 'Ich weiß es nicht' — also raten Modelle lieber (Paper 'Why Language Models Hallucinate', 2025). Extremfall aus der eigenen Model Card: gpt-oss-120b lag bei 78 Prozent Fehlern auf SimpleQA — einem Test ganz OHNE Quellen, der nur das Erinnern prüft. Achtung beim Vergleichen: Das Vectara-Leaderboard (HHEM) misst etwas anderes, nämlich ob eine Zusammenfassung vom mitgelieferten Dokument abweicht; dort bleiben gute Modelle unter 2 Prozent. Zwei Messungen, zwei Fragen — die Zahlen lassen sich nicht ineinander umrechnen, auch wenn beide in dieselbe Richtung zeigen: Mit Quelle im Kontext rät ein Modell weniger. Häufige Ursache sind veraltete oder fehlende Quellen — dagegen helfen eine Faktenkur mit aktuellen RAG-Quellen und Grounding, belohnte Enthaltung und niedrigere Temperatur; Schlaf hilft nicht."},
  {kat:"training", t:"Checkpoints: die Lebensversicherung", txt:"Jeder ernsthafte Trainingslauf speichert regelmäßig Checkpoints — beim OPT-175B-Training rollte Meta bei Loss-Explosionen dutzendfach zu einem früheren Stand zurück und senkte die Lernrate (OPT-Logbuch 2022). Übertraining verschwindet nicht durch Ausruhen — nur der Rollback stellt den alten Stand her. Vorbeugend gegen katastrophales Vergessen beim Feintuning: Early Stopping und Replay, also 10 bis 30 Prozent Originaldaten untermischen (Continual-Learning-Forschung)."},
  {kat:"training", t:"Wiederholungsschleifen", txt:"Greedy-Dekodierung endet in Endlosschleifen — Holtzman et al. 2019 zeigten es und erfanden Nucleus Sampling als Gegenmittel. Die Qwen3 Model Card rät ausdrücklich zu Temperatur 0,6, Top-p 0,95 und Presence Penalty gegen Endlos-Wiederholungen (Qwen3 Model Card 2025). Und wer Modelle unkritisch immer wieder nur mit eigenen Ausgaben füttert, riskiert Kollaps: Die seltenen Randfälle sterben zuerst (Shumailov, Nature 2024) — ein reales Risiko, kein Naturgesetz; frische menschliche Daten halten die Vielfalt am Leben."}
];
