/* Exportiert dieselben Vektoren, die das Spiel verwendet. Kein Raster-Freistellen. */
const fs=require('fs'),path=require('path'),vm=require('vm');
const dir=path.resolve(__dirname,'../assets/rechenhaus');fs.mkdirSync(dir,{recursive:true});
const c=vm.createContext({console});for(const f of ['grafik.js','rechenhaus_objekte.js','rechenhaus.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,f),'utf8'),c);
const entries=[];function out(file,svg,label,type='objekt'){fs.writeFileSync(path.join(dir,file),svg);entries.push({datei:file,name:label,typ:type,format:'SVG',transparent:type!=='hintergrund',viewBox:svg.match(/viewBox="([^"]+)"/)[1]});}
const names={wind_klein:'Windrad klein · 5 kW',wind_mittel:'Windrad mittel · 20 kW',wind_gross:'Windrad groß · 50 kW',nachbarkabel:'Das Kabel vom Nachbarn',solarpanel_400w:'Solarpanel · 400 W',solarpanel_600w:'Solarpanel · 600 W',solarfeld:'Solarfeld · vier 600-W-Module',akku:'Akkuspeicher',kraftwerk:'Fossiles Kraftwerk',transformator:'Transformator',stromverteiler:'Stromverteiler',pc:'PC mit Bildschirm',serverschrank:'Serverschrank · vier Knoten'};
for(const [id,label]of Object.entries(names))out(id+'.svg',c.rhObjektSvg(id),label);
for(const [st,n,base]of [[0,4,'schuppen'],[1,6,'nerd'],[2,10,'zentrum']]){
 const h=st===1?572:512,grid=c.rhDachSvg({stufe:st,pv:[]}).replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '),filled=c.rhDachSvg({stufe:st,pv:Array(n).fill(600)}),body=x=>x.slice(x.indexOf('>')+1,x.lastIndexOf('</svg>'));
 out('dach_'+n+'_overlay.svg',grid,n+' exakt ausgerichtete Dachplätze · Overlay','overlay');
 const p=[[[232,52],[535,24],[629,174],[328,211]],[[199,114],[526,43],[372,264],[74,284]],[[222,79],[511,33],[366,198],[75,220]]][st];
 const minx=Math.min(...p.map(x=>x[0]))-8,miny=Math.min(...p.map(x=>x[1]))-8,maxx=Math.max(...p.map(x=>x[0]))+8,maxy=Math.max(...p.map(x=>x[1]))+8;
 const edge='<polygon points="'+p.map(x=>x.join(',')).join(' ')+'" fill="'+(st===2?'#81a392':'#cc965d')+'" stroke="#654328" stroke-width="6" stroke-linejoin="round"/>';
 for(const [suffix,label,g]of [['felder','freie Plätze',grid],['belegt','mit Solarmodulen',filled]])out('dach_'+n+'_'+suffix+'.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="'+[minx,miny,maxx-minx,maxy-miny].join(' ')+'">'+edge+body(g)+'</svg>','Dachfläche · '+n+' '+label,'dach');
 const png=fs.readFileSync(path.join(dir,base+'.png')).toString('base64');
 out('gebaeude_'+n+'_felder.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 768 '+h+'"><image width="768" height="'+h+'" href="data:image/png;base64,'+png+'"/>'+body(grid)+'</svg>',['Geräteschuppen','Nerdtümpel','Rechenzentrum'][st]+' · '+n+' Dachplätze','gebaeude');
}
for(const [id,label]of [['morgen','Morgenwiese'],['blumen','Blumenwiese'],['spaetsommer','Spätsommerwiese']])out('hintergrund_'+id+'.svg',c.rhHintergrundSvg(id).replace('width="100%" height="100%"','width="1600" height="900"'),label,'hintergrund');
for(const name of ['schuppen','nerd','zentrum','raum','trink_schwein','trink_huhn','trink_kuh','trink_esel','trink_lama','trink_dino']){const b=fs.readFileSync(path.join(dir,name+'.png'));entries.push({datei:name+'.png',name:name.replaceAll('_',' '),typ:name==='raum'?'innenraum':'raster',format:'PNG',transparent:name!=='raum',breite:b.readUInt32BE(16),hoehe:b.readUInt32BE(20)});}
fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify({stand:'2026-08-30',stil:'Originale Modellhof-Palette, transparente Einzelobjekte',teich:{viewBox:[0,0,1600,900],cx:950,cy:712,rx:132,ry:38,preserveAspectRatio:'xMidYMax slice'},hinweis:'Alle SVG sind selbständig nutzbar. Gebäude-SVG enthalten ihre PNG-Daten. Keine externen Bild- oder Schriftdateien nötig. Dach-Overlays passen unverändert über das zugehörige Gebäude-PNG; kombinierte Gebäude-SVG sind bereits fertig.',dateien:entries},null,2));
const groups=[['Objekte','objekt'],['Dächer mit 4, 6 und 10 Plätzen','dach'],['Gebäude mit fertigen Dachplätzen','gebaeude'],['Drei Hofhintergründe · Teich unverändert','hintergrund'],['Originalstil-Gebäude, Innenraum und Trinkposen','raster'],['Innenraum','innenraum']];
const esc=x=>x.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const gallery=groups.map(([n,t])=>'<h2>'+n+'</h2><div class="grid '+(t==='hintergrund'?'weit':'')+'">'+entries.filter(x=>x.typ===t).map(e=>'<article><a href="'+e.datei+'"><div class="bild"><img loading="lazy" src="'+e.datei+'" alt="'+esc(e.name)+'"></div></a><h3>'+e.name+'</h3><p>'+e.format+' · '+(e.transparent?'transparent':'deckend')+'</p><a download href="'+e.datei+'">Datei herunterladen</a></article>').join('')+'</div>').join('');
fs.writeFileSync(path.join(dir,'index.html'),'<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Modellhof · fertige Grafiken</title><style>*{box-sizing:border-box}body{margin:0;padding:30px;background:#f5e8ca;color:#4a2c15;font:15px/1.5 system-ui,sans-serif}main{max-width:1200px;margin:auto}h1,h2,h3{font-family:Georgia,serif}h1{font-size:32px}h2{margin-top:35px;font-size:23px}h3{font-size:17px;margin:12px 0 3px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:15px}.weit{grid-template-columns:repeat(auto-fit,minmax(310px,1fr))}article{padding:12px;background:#fff7e4;border:2px solid #b89769;border-radius:10px}.bild{height:190px;background:#7ec95a;border-radius:6px;display:flex;align-items:center;justify-content:center}.bild img{display:block;max-width:100%;max-height:100%;object-fit:contain}.weit .bild{height:auto;aspect-ratio:16/9}.weit img{width:100%;height:100%}p{margin:4px 0 12px}a{color:#356e61;font-weight:700}code{word-break:break-word}aside{padding:16px;background:#e0e9c8;border-left:4px solid #668f62}footer{margin-top:35px}</style><main><h1>Ein kleiner Hof, fertig zum Einbauen.</h1><p>Alle Objekte sind einzeln nutzbar, ohne Freistellen, Zuschneiden oder Entfernen eines Rahmens. Die grüne Wiese hier gehört nur zur Vorschau.</p><aside><b>Direkt verwenden:</b> SVG oder PNG herunterladen und als Bild einbinden. Die drei Gebäude-SVG enthalten Gebäude und Dachplätze bereits zusammen. Die separaten <code>dach_*_overlay.svg</code> liegen deckungsgleich über den jeweiligen Gebäude-PNGs. Die reinen Dachflächen sind eigenständige Vektorobjekte.</aside>'+gallery+'<footer><p>Die 3 Hintergründe haben dieselbe Szene von 1600 × 900 und denselben Teichmittelpunkt (950, 712), Wasserellipse 132 × 38. Im Spiel unter <b>Rechenhaus → Hofansicht</b> wählen. Die ursprüngliche Wiese bleibt voreingestellt.</p><a href="manifest.json">Asset-Verzeichnis und Koordinaten</a> · <a href="../../modellhof_game.html">Spiel öffnen</a></footer></main></html>');
console.log(entries.length+' direkt nutzbare Grafiken + Vorschau + Manifest exportiert.');
