// Nur lokale Prüfansicht. Kein Debug-/Cheat-Menü in der ausgelieferten Spieldatei.
const fs=require('fs'),path=require('path');let html=fs.readFileSync(path.join(__dirname,'../modellhof_game.html'),'utf8');
const qa=`<div id="qa" style="position:fixed;top:0;left:0;z-index:9999;background:#fff8df;border:2px solid #543c28;padding:4px;font:12px sans-serif"><b>PRÜFANSICHT</b> <button onclick="qaStand(0)">QA Schuppen</button> <button onclick="qaStand(1)">QA Nerdtümpel</button> <button onclick="qaStand(2)">QA Rechenzentrum</button> <button onclick="qaTrink(-1)">QA links trinken</button> <button onclick="qaTrink(1)">QA rechts trinken</button> <button onclick="qaLaufen()">QA zum Teich laufen</button> <select aria-label="QA Tierart" onchange="S.tierArt=this.value;maskenCss();wieseNeu()"><option>schwein</option><option>huhn</option><option>kuh</option><option>esel</option><option>lama</option><option>dino</option></select></div>
<script>
function qaStand(st){S=frischerStand();S.kredit=5000000;S.einfFertig=true;S.hilfeGesehen=true;S.rechenhaus.stufe=st;const r=rh();r.netzKW=[12,100,600][st];r.nachbar=true;r.pv=Array(RH_STUFEN[st].dach).fill(RH_STUFEN[st].wp);r.akku=[10,80,600][st];r.soc=r.akku*.6;r.wind=st?[0,1,2,2,2,2]:[];r.gen=st?st===1?1:4:-1;r.events={'1:0':true,'1:1':true,'1:2':true,'2:0':true,'2:1':true,'2:2':true};r.racks=st?Array.from({length:st===1?8:64},(_,i)=>i):[];if(st===2)S.buchten=[];const id=Object.keys(MODELLE).find(id=>MODELLE[id].tier===0&&!MODELLE[id].puzzle);const p=neuesTier(id);p.x=45;p.y=77;p.sitzung={tokens:8000,notizen:['Wichtige Notiz bleibt'],wechsel:0};S.tiere=[p];rhSelected=null;alles();blattZu();}
function qaTrink(side){const p=S.tiere[0];if(!p)return;blattZu();const g=rhTeichBoxLesen();p.x=g.x+side*(g.rx+2.2);p.y=g.y+.8;p._liegt=0;p._trink={phase:'trink',seite:side,t:-20};p._durst=0;wieseNeu();}
function qaLaufen(){const p=S.tiere[0];if(!p)return;blattZu();p._trink=null;p.x=40;p.y=75;p._durst=0;p._liegt=0;wieseNeu();}
</script>`;
html=html.replace(/const KEY="modellhof_[^"]+"/, 'const KEY="modellhof_rechenhaus_qa"');
html=html.replace('</body>',qa.replace("r.gen=st?st===1?1:4:-1;","r.gen=st?st===1?1:4:-1;r.solarfelder=st===2?3:0;")+'</body>');fs.writeFileSync(path.join(__dirname,'rechenhaus_qa.html'),html);
fs.writeFileSync(path.join(__dirname,'rechenhaus_mobile_qa.html'),'<!doctype html><html lang="de"><meta charset="UTF-8"><title>Modellhof mobile Prüfung</title><body style="margin:0;background:#5b4d3b"><div style="text-align:center;padding:8px"><button onclick="mob(0,\'raum\')">Mobil: Schuppen</button> <button onclick="mob(2,\'raum\')">Mobil: 64 Racks</button> <button onclick="mob(2,\'energie\')">Mobil: Energie</button> <button onclick="mob(0,\'ansicht\')">Mobil: Hintergründe</button></div><iframe id="spiel" title="Modellhof bei 390 × 844" src="rechenhaus_qa.html" style="width:390px;height:844px;border:0;display:block;margin:auto"></iframe><script>function mob(st,view){const w=document.getElementById("spiel").contentWindow;w.qaStand(st);w.document.getElementById("qa").style.display="none";w.zeigeRechenhaus(view);}</script></body></html>');
console.log('Zwei lokale Browser-Prüfansichten gebaut.');
