/* Regressionsprüfung des vollständigen Builds, inklusive Finanz- und Energie-Invarianten. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../modellhof_game.html'),'utf8');
const source=html.match(/<script>([\s\S]*?)<\/script>/)[1].split('/* Boot-Sequenz */')[0];
function environment(){const nodes=new Map(),timers=[];
 const el=()=>({innerHTML:'',textContent:'',value:'',style:{setProperty(){}},dataset:{},classList:{add(){},remove(){},contains:()=>false},appendChild(){},remove(){},before(){},setAttribute(){},querySelector:()=>el(),querySelectorAll:()=>[],addEventListener(){},clientWidth:390,clientHeight:840});
 const document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,el());return nodes.get(id);},createElement:el,querySelector:()=>el(),querySelectorAll:()=>[],addEventListener(){},body:el(),head:el(),visibilityState:'visible'};
 const storage={};const c={console,Math:Object.create(Math),JSON,Date,Object,Array,Number,String,Boolean,RegExp,Map,Set,isNaN,parseInt,parseFloat,setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout(){},setInterval:()=>0,clearInterval(){},requestAnimationFrame(){},performance:{now:()=>0},document,window:{matchMedia:()=>({matches:false})},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v,removeItem:k=>delete storage[k]},confirm:()=>true,prompt:()=>null,alert(){},navigator:{},location:{reload(){}},URL:{},Blob:function(){},Image:function(){}};
 vm.createContext(c);vm.runInContext(source,c,{timeout:30000});
 vm.runInContext(`Object.assign(globalThis,{HL_AUFTRAEGE,HL_EVENTS,HL_TEILE,MODELLE,TECHNIKEN,GPUS,WERTE,KEY,dsWahrscheinlichkeit});globalThis.reset=()=>{S=frischerStand();S.einfFertig=true;return S};globalThis.state=()=>S;globalThis.choose=(jid,w)=>{hlAuswahl[jid]=w};globalThis.restore=o=>{S=standAuffuellen(o);return S};globalThis.__zeigeNachtSetup=zeigeNachtSetup;`,c);
 for(const k of ['alles','kopfNeu','wieseNeu','schilderNeu','tickerNeu','tickerLauf','zeigeBericht','zeigeJobs','zeigeNachtSetup','zeigeRechenhaus','zeigeWissenswerkstatt','zeigeTier','blattAuf','blattZu','melde','questPruefe','uhrAnzeige','figurDeko'])c[k]=()=>{};
 c.Math.random=()=>.1;c.timers=timers;c.storage=storage;return c;
}
const c=environment();let s,passed=0;const results=[];
function reset(){while(c.timers.length)c.timers.shift()();s=c.reset();return s;}
function add(id,slot=0){const p=c.neuesTier(id);s.tiere.push(p);if(!s.buchten[slot])s.buchten[slot]={...s.buchten[0],id:'b'+(slot+1),rhSlot:'pc:'+slot,tier:null};p.bucht=s.buchten[slot].id;s.buchten[slot].tier=p.uid;return p;}
function mikro(){return c.hlJobNeu(0);}
function contract(index){const v=c.HL_AUFTRAEGE[index];return {id:'x'+s.zaehler++,t:v.t,b:v.b,tier:v.tier,art:v.art,kunde:v.kunde,tage:v.tage,puffer:1,frisch:s.tag,anf:Object.assign({},...v.rollen.map(r=>r[1])),rollen:v.rollen.map(([n,anf])=>({n,anf})),teile:v.teile||[],ctxMin:4,mtokTag:.04,lohnBasis:v.lohn,einheiten:40,latenz:1,dsgvo:!!v.lokal};}
function start(j,w){s.jobs.push(j);c.choose(j.id,w);c.hlTeamStart(j.id);assert.ok(j.team,'Vertrag nicht gestartet');}
function tick(){c.ausfuehrenTagesWechsel();}
function test(n,f){try{reset();f();results.push({name:n,ok:true});passed++;console.log('PASS '+n);}catch(e){results.push({name:n,ok:false,error:e.stack});console.log('FAIL '+n+' :: '+e.message);}}
test('Alte RAG-Käufe bleiben erhalten, Migration idempotent',()=>{delete s.hofloop;s.setup_rag=true;const o=c.restore(s);assert.equal(Object.keys(o.hofloop.teile).length,4);assert.ok(c.hlRagBereit());const a=JSON.stringify(o);c.standAuffuellen(o);assert.equal(JSON.stringify(o),a);});
test('Energie-Vorschau ist vollständig nebenwirkungsfrei',()=>{add('falcon-h1-tiny');const vorher=JSON.stringify(s);c.rhVorschau();c.rhVorschau();assert.equal(JSON.stringify(s),vorher);});
test('0,6B-Modell kann alle vier Mikroaufgaben erfüllen',()=>{const id=Object.keys(c.MODELLE).find(k=>c.MODELLE[k].pT===.6),p=add(id);for(let i=0;i<4;i++){const j=contract(i),q=c.hlTeamCheck(j,{0:p.uid});assert.ok(q.ok,c.HL_AUFTRAEGE[i].t+': '+q.gruende);assert.ok(q.anteil>.95);}});
test('Nachtplanung rechnet noch keinen Tag ab',()=>{const k=s.kredit;c.tagBeenden();assert.equal(s.tag,1);assert.equal(s.kredit,k);assert.equal(s.hofloop.phase,'planung');});
test('Doppelklick auf Nachtstart führt zu genau einem Tageswechsel',()=>{c.tagBeenden();assert.equal(c.starteNachtSchicht(),true);assert.equal(c.starteNachtSchicht(),false);assert.equal(s.tag,1);while(c.timers.length)c.timers.shift()();assert.equal(s.tag,2);assert.equal(s.hofloop.phase,'tag');});
test('Laden während Mondanimation stellt ungebuchte Planung wieder her',()=>{s.hofloop.phase='laeuft';s.hofloop.nacht=[];const o=JSON.parse(JSON.stringify(s));c.restore(o);assert.equal(o.hofloop.phase,'planung');assert.equal(o.tag,1);});
test('Zwei Modelle ergänzen Fähigkeiten, ohne sie zu addieren',()=>{const a=add('smollm3-3b'),b=add('qwen35-4b',1);a.w.schreiben=20;b.w.schreiben=65;const j=contract(4);assert.ok(c.hlTeamCheck(j,{0:a.uid,1:b.uid}).ok);assert.equal(c.hlTeamCheck(j,{0:a.uid,1:a.uid}).ok,false);});
test('Team wird einmal bezahlt, zwei Arbeitstage und beide Modelle freigegeben',()=>{const a=add('smollm3-3b'),b=add('qwen35-4b',1);for(const p of [a,b])for(const k in p.w)p.w[k]=75;const j=contract(4);j.mtok=7;j.mtokTag=3.5;start(j,{0:a.uid,1:b.uid});tick();assert.ok(j.team.mtokRest>0&&j.team.rest>=1,'Stunden-Modell: nach einem Tag ist Restarbeit übrig');assert.equal(s.statistik.jobs,0);for(let k=0;k<6&&j.team;k++)tick();assert.equal(s.statistik.jobs,1);assert.equal(s.journal.filter(x=>x.kat==='job'&&x.t.startsWith(j.t)).length,1);assert.equal(a.status,'frei');assert.equal(b.status,'frei');});
test('Doppelte Annahme desselben Auftrags ist gesperrt',()=>{const a=add('smollm3-3b'),b=add('qwen35-4b',1),j=contract(0);start(j,{0:a.uid});c.jobAnnehmen(j.id,b.uid);assert.equal(b.status,'frei');});
test('auf eigener Hardware gilt für jede Stufe der Kette',()=>{const p=c.neueLizenz(Object.keys(vm.runInContext('LEIHMODELLE',c))[0]);s.tiere.push(p);const j=contract(0);j.dsgvo=true;assert.equal(c.hlTeamCheck(j,{0:p.uid}).ok,false);});
test('Kaufpreis wird bei Vertragsschluss eingefroren',()=>{const p=add('qwen35-4b'),j=contract(0);start(j,{0:p.uid});const preis=c.jobLohnGesamt(j);s.events=[{id:'x',effekt:{typ:'nachfrage',wert:-.8,tage:2}}];assert.equal(c.jobLohnGesamt(j),preis);});
test('Frist läuft bei Energiepause weiter; Strafe statt Gratisbezahlung',()=>{const p=add('qwen35-4b'),j=contract(0);s.hofloop.energie[p.uid]='eigen';start(j,{0:p.uid});tick();assert.equal(j.team.rest,1);tick();assert.equal(p.status,'frei');assert.equal(s.statistik.jobs,0);assert.ok(s.journal.some(x=>x.kat==='strafe'));});
test('Eigenstrom ohne Anlage kann nicht heimlich Netzstrom verbrauchen',()=>{const p=add('qwen35-4b');p.status='job';s.hofloop.energie[p.uid]='eigen';const a=c.rhVorschau();assert.equal(c.hlVersorgung(p,a),0);assert.ok(a.netz<3)   /* Ära 8: Leerlauf × PUE + Grundlast ≈ 2,2 kWh */;assert.ok(a.fehl>1);});
test('Netzausfall erst ab Stufe 5, Cloud unabhängig',()=>{const p=add('qwen35-4b');p.status='job';s.hofloop.ereignis={id:'ausfall'};assert.equal(c.hlVersorgung(p,c.rhVorschau()),1);s.xp=900;assert.ok(c.hlVersorgung(p,c.rhVorschau())<.98);assert.equal(c.hlVersorgung({api:true},c.rhVorschau()),1);});
test('Wind oder voller Akku kann Nacht versorgen; Solar allein nicht',()=>{const p=add('qwen35-4b');s.hofloop.plan[p.uid]={art:'synth',fokus:'treue'};s.hofloop.energie[p.uid]='eigen';s.rechenhaus.pv=[400,400,400,400];assert.equal(c.hlVersorgung(p,c.rhVorschau(),true),0);s.rechenhaus.akku=10;s.rechenhaus.soc=10;assert.ok(c.hlVersorgung(p,c.rhVorschau(),true)>.98);});
test('Halber Tarif nur in Nachtstunden, keine pauschale Erstattung',()=>{const r=c.rhNeu(),last=Array(24).fill(1);r.netzKW=10;const a=c.rhSim(r,last,1,.48,{hofnacht:true,normal:true});assert.ok(Math.abs(a.netzKosten-(16*.48+8*.24))<1e-8);assert.ok(Math.abs(a.nachtKosten-8*.24)<1e-8);});
test('Pipeline für 210 €, alle Bausteine für 470 €, kein Doppelabbuchen',()=>{const vor=s.kredit;c.hlBauteilKauf('embedding');assert.equal(s.kredit,vor);for(const k of ['vector','embedding','ocr','reranker'])c.hlBauteilKauf(k);assert.equal(vor-s.kredit,470);assert.ok(c.hlRagBereit());c.hlBauteilKauf('vector');assert.equal(vor-s.kredit,470);});
test('Neue Quellen invalidieren Index; Reindex verändert keine Gewichte',()=>{const p=add('qwen35-4b');for(const k of ['vector','embedding'])c.hlBauteilKauf(k);const before=JSON.stringify(p.w);s.hofloop.indexTag=1;s.tag=8;assert.ok(c.hlIndexAlter()>3);s.hofloop.nacht=[{uid:p.uid,q:{art:'reindex'},stunden:2}];c.hlNachtAbrechnen(c.rhVorschau(),{zeilen:[]});assert.equal(s.hofloop.indexTag,9);assert.equal(JSON.stringify(p.w),before);});
test('LoRA nachts nutzt reale Stunden und bestehendes Trainingsverfahren',()=>{const p=add('qwen35-4b');s.xp=300;s.forschung.sft=true;s.forschung.lora=true;const q={art:'lora',fokus:'treue'},stunden=c.hlNachtDauer(p,q);assert.ok(stunden>0&&stunden<8);const vor=s.kredit;s.hofloop.nacht=[{uid:p.uid,q,stunden}];c.hlNachtAbrechnen(c.rhVorschau(),{zeilen:[]});assert.ok(s.kredit<vor);assert.equal(s.statistik.trainings,1);assert.ok(p.adapters.length>0);});
test('Nachttraining über mehrere Nächte arbeitet tagsüber nicht weiter',()=>{const p=add('qwen35-4b');s.xp=900;s.buchten[0].gpu='a100';s.daten.beispiele=20;p.status='training';p.training={id:'sft',fokus:'treue',futter:'beispiele',bucht:p.bucht,cloud:false,nurNacht:true,nachtRest:20};p.rest=3;tick();assert.equal(p.training.nachtRest,20);assert.equal(p.rest,3);});
test('Ungültiges „Training fortsetzen“ ohne laufendes Nachttraining wird ohne Nullzugriff abgewiesen',()=>{const p=add('qwen35-4b');s.hofloop.plan[p.uid]={art:'weiter',fokus:'treue'};assert.match(c.hlNachtPruefung(p,s.hofloop.plan[p.uid]),/Kein Nachttraining/);assert.doesNotThrow(()=>c.__zeigeNachtSetup());});
test('Unversorgte Nacht erzeugt weder Training noch Daten',()=>{const p=add('qwen35-4b');s.hofloop.energie[p.uid]='eigen';s.hofloop.nacht=[{uid:p.uid,q:{art:'synth',fokus:'treue'},stunden:6}];const a=c.rhVorschau();c.hlNachtAbrechnen(a,{zeilen:[]});assert.equal(s.daten.synth||0,0);});
test('Synthetik erzeugt nachvollziehbare Charge und kostet Kapazität',()=>{const p=add('qwen35-4b');s.hofloop.nacht=[{uid:p.uid,q:{art:'synth',fokus:'treue'},stunden:6}];const a=c.rhVorschau();assert.ok(a.nachtKwh>1);c.hlNachtAbrechnen(a,{zeilen:[]});assert.ok(s.daten.synth>=8&&s.daten.synth<=40);assert.ok(s.synthChargen[0].quelle.includes('Nacht'));});
test('Lehrer kann nicht doppelt für zwei Schüler gebucht werden; Nacht fällt sicher auf Ruhe zurück',()=>{const a=add('smollm3-3b'),b=add('smollm3-3b',1),l=add('qwen35-4b',2);l.w.treue=90;for(const p of [a,b])s.hofloop.plan[p.uid]={art:'distill',fokus:'treue',lehrer:l.uid};c.tagBeenden();assert.equal(c.starteNachtSchicht(),true);assert.equal(s.hofloop.plan[a.uid].art,'ruhe');assert.equal(s.hofloop.plan[b.uid].art,'ruhe');});
test('Zahlungsunfähiger Nachtplan fällt auf kostenlose Ruhe zurück und blockiert den Tag nicht',()=>{const p=add('qwen35-4b');s.xp=300;s.forschung.sft=true;s.forschung.lora=true;s.daten.beispiele=100;s.kredit=-21;s.hofloop.plan[p.uid]={art:'lora',fokus:'treue',futter:'beispiele'};c.tagBeenden();assert.equal(c.starteNachtSchicht(),true,'Nachtschicht darf nicht blockieren');assert.equal(s.hofloop.plan[p.uid].art,'ruhe','Training muss auf Ruhe fallen');while(c.timers.length)c.timers.shift()();assert.equal(s.tag,2,'Tag muss fortschreiten');assert.equal(s.hofloop.phase,'tag');});
test('Qualitätsserie belohnt sauber, Reklamation setzt nur Serie zurück',()=>{const j=contract(0),b={zeilen:[]};for(let i=0;i<3;i++)c.hlQualitaet(j,true,b);assert.equal(s.hofloop.serie,3);assert.ok(s.journal.some(x=>x.t.includes('Qualitätsprämie')));c.hlQualitaet(j,false,b);assert.equal(s.hofloop.serie,0);assert.equal(s.hofloop.best,3);});
test('Aktuelle Dreistufenprüfung wird nach Konfigurationsänderung ungültig',()=>{const p=add('qwen35-4b'),j=contract(0);s.jobs.push(j);c.hlPruefen(p.uid,j.id);assert.equal(c.hlGeprueft(p,j),true);const k=s.kredit;c.hlPruefen(p.uid,j.id);assert.equal(s.kredit,k);p.temp='kreativ';assert.equal(c.hlGeprueft(p,j),false);});
test('Energie bleibt auch mit Prioritäten, Akku und Netzausfall erhalten',()=>{const p=add('qwen35-4b'),q=add('smollm3-3b',1);p.status=q.status='job';s.hofloop.energie[p.uid]='eigen';Object.assign(s.rechenhaus,{akku:5,soc:2,pv:[400,400],wind:[0],netzKW:.2});for(let day=1;day<=20;day++){s.tag=day;const a=c.rhVorschau();const rein=a.pv+a.wind+a.netz+a.nachbar+a.fossil+a.socStart,raus=a.last-a.fehl+a.export+a.soc+a.verlust+(a.abregelung||0);assert.ok(Math.abs(rein-raus)<1e-7,`${rein} != ${raus}`);assert.ok(a.soc>=0&&a.soc<=5);}});
test('Quellenänderung macht auch den jungen Index sofort ungültig',()=>{s.hofloop.teile={vector:true,embedding:true};s.hofloop.indexTag=1;s.hofloop.indexVeraltet=true;s.tag=2;assert.ok(c.hlIndexAlter()>3);});
test('Fehlgeschlagene Nachtschicht zählt nicht als Projektfortschritt',()=>{const p=add('qwen35-4b');s.hofloop.energie[p.uid]='eigen';s.hofloop.nacht=[{uid:p.uid,q:{art:'synth',fokus:'treue'},stunden:6}];c.hlNachtAbrechnen(c.rhVorschau(),{zeilen:[]});assert.equal(s.hofloop.naechteArbeit||0,0);});
test('Hofprojekt zahlt genau einmal und nur während seiner Spielwoche',()=>{c.hlProjektWaehlen('klein');s.hofloop.mikroSauber=4;const b={zeilen:[]},vor=s.kredit;c.hlProjektPruefen(b);c.hlProjektPruefen(b);assert.equal(s.kredit-vor,130);s.hofloop.projekt.erledigt=false;s.tag=9;c.hlProjektPruefen(b);assert.equal(s.kredit-vor,130);});
test('LoRA-Risiko verändert niemals die eingefrorene Basis',()=>{const p=add('qwen35-4b'),vor=JSON.stringify(p.w);c.Math.random=()=>0;p.training={id:'lora',fokus:'treue',futter:'beispiele'};c.trainingAbschliessen(p,{zeilen:[]});assert.equal(JSON.stringify(p.w),vor);assert.ok(p.adapters.length);c.Math.random=()=>.1;});
test('Tagesbericht stimmt auch beim Kürzen des 500-Zeilen-Journals',()=>{for(let i=0;i<499;i++)c.buche(.01,'sonst','Journalgrenze');const p=add('qwen35-4b'),j=contract(0);start(j,{0:p.uid});const vor=s.kredit;tick();assert.ok(s.journal.length<499);assert.ok(Math.abs((s.kredit-vor)-(s.letzterBericht.einnahmen-s.letzterBericht.ausgaben))<.001);});
test('120 Tage über 8 Seeds: kleiner Spezialist bleibt wirtschaftlich',()=>{const runs=[];for(const seed of [3,7,11,42,99,123,777,904]){reset();let rnd=seed;c.Math.random=()=>{rnd=(rnd*1664525+1013904223)>>>0;return rnd/4294967296;};const p=add(Object.keys(c.MODELLE).find(k=>c.MODELLE[k].pT===.6));c.buche(-c.MODELLE[p.modell].preis,'kauf','Startmodell');s.jobs=[mikro(),mikro(),mikro()];let min=s.kredit;
  for(let d=0;d<120;d++){if(p.status==='frei'){if(p.zustand<75)c.auffrischen(p.uid);const j=s.jobs.find(j=>!j.team&&!s.tiere.some(t=>t.job===j.id)&&!(typeof c.dsWahrscheinlichkeit==='function'&&c.dsWahrscheinlichkeit(j,[p]).p>0)&&c.hlTeamCheck(j,Object.fromEntries(c.hlRollen(j).map((r,i)=>[i,p.uid]))).ok);if(j)c.jobAnnehmen(j.id,p.uid);}tick();assert.equal(s.tag,d+2);assert.ok(Number.isFinite(s.kredit));assert.ok(Math.abs(s.kredit-(2500+s.statistik.einnahmen-s.statistik.ausgaben))<.001);min=Math.min(min,s.kredit);}
  runs.push({seed,cash:s.kredit,min,jobs:s.statistik.jobs});assert.ok(s.kredit>2500,'Seed '+seed+' Endstand '+s.kredit);assert.ok(min>0,'Seed '+seed+' Minimum '+min);}
 fs.writeFileSync(path.join(__dirname,'../BALANCE_HOFLOOP.json'),JSON.stringify(runs,null,2));});
fs.writeFileSync(path.join(__dirname,'../PRUEFERGEBNIS_HOFLOOP.json'),JSON.stringify({passed,total:results.length,results},null,2));
test('Jede Auftragsvorlage verlangt nur Werte, die es wirklich gibt (v9.8: „stil" existierte nie)',()=>{
  const erlaubt=Object.keys(c.WERTE); const fehler=[];
  for(const v of c.HL_AUFTRAEGE){ for(const [n,anf] of (v.rollen||[])) for(const k of Object.keys(anf||{})) if(!erlaubt.includes(k)) fehler.push(v.key+"/"+n+": "+k); }
  assert.deepEqual(fehler,[],"unbekannte Anforderungen: "+fehler.join(", "));
  const gross=c.HL_AUFTRAEGE.filter(v=>v.gross); assert.ok(gross.length>=2,"Großaufträge vorhanden");
  for(const v of gross){ const p=add('qwen35-4b'); Object.keys(c.WERTE).forEach(k=>p.w[k]=99);
    for(const [n,anf] of v.rollen) for(const [k,w] of Object.entries(anf)) assert.ok(p.w[k]>=w,v.key+": "+k+" nicht erfüllbar"); } });
console.log(`${passed}/${results.length} bestanden`);process.exitCode=passed===results.length?0:1;
